app/urls.py
from django.contrib.gis import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('registration.backends.simple.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('', include('logger.urls')),
    path('accounts/profile/', include('logger.urls')),
]

logger/urls.py
from django.urls import path, include
from .views import SensorList
from . import views

urlpatterns = [
    path('', SensorList.as_view(), name='index'),
    path('sensors/data/add', views.add_data, name='add_data'),
    path('sensors/map', views.map_sensors, name='map_sensor'),
    path('sensors/heatmap', views.heatmap, name='heatmap'),
    path('sensors/detail/<int:sensor_id>', views.sensor_detail, name='detail_sensor'),
    path('sensors/export/<int:sensor_id>', views.sensor_export, name='export_sensor'),
    path('sensors/export/', views.sensor_export_poly, name='export_poly'),
    path('sensors/crud/',  include('crudbuilder.urls')),
]

logger/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField()
    address = models.CharField(max_length=255)
    organization = models.CharField(max_length=100)
    country = CountryField()

class Sensor(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    coordinates = models.PointField(null=True, blank=True,)
    def __str__(self):
        return self.name

class SensorData(models.Model):
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    particulate_matter = models.FloatField()
    received_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField()

class Download(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    sensors = models.ManyToManyField(Sensor)
    start_date = models.DateField()
    end_date = models.DateField()

logger/forms.py
from django import forms
import datetime

class SensorExportForm(forms.Form):
    sensor = forms.IntegerField(label='Sensor')
    start_date = forms.DateField(label='Start Date',initial=datetime.date.today)
    end_date = forms.DateField(label='End Date',initial=datetime.date.today)

class MulSensorExportForm(forms.Form):
    mul_sensors = forms.CharField(label='Sensors')
    start_date = forms.DateField(label='Start Date',initial=datetime.date.today)
    end_date = forms.DateField(label='End Date',initial=datetime.date.today)

logger/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import ListView
from .models import *
from django.views.decorators.csrf import csrf_exempt
import datetime
import json

from .forms import SensorExportForm
from .forms import MulSensorExportForm
from .resources import SensorDataResource
from .resources import MulSensorDataResource

from django.contrib.auth.decorators import login_required

class SensorList(ListView):
    model = Sensor

@login_required
def sensor_export_poly(request):

    if request.method == 'POST':
        form = MulSensorExportForm(request.POST)

        if form.is_valid():
            sensor_data_resource = MulSensorDataResource()
            sensors = Sensor.objects.filter(pk__in=json.loads(form.cleaned_data['mul_sensors']))
            queryset = SensorData.objects.filter(sensor__in=sensors).filter(created_at__gte = form.cleaned_data['start_date']).filter(created_at__lte = form.cleaned_data['end_date'])
            dataset = sensor_data_resource.export(queryset)

            download = Download()
            download.owner = request.user
            download.sensors_set = sensors
            download.start_date = form.cleaned_data['start_date']
            download.end_date = form.cleaned_data['end_date']
            download.save()

            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="sensors.csv"'
            return response
    else:
        sensors = Sensor.objects.all()
        form = SensorExportForm()
        date = datetime.datetime.today().strftime('%Y-%m-%d')
        return render(request, 'logger/export-poly.html', {'form': form, 'sensors': sensors,'date': date})

@login_required
def sensor_export(request,sensor_id):

    if request.method == 'POST':
        form = SensorExportForm(request.POST)

        if form.is_valid():
            sensor_data_resource = SensorDataResource()
            sensor = Sensor.objects.get(id=sensor_id)
            queryset = SensorData.objects.filter(sensor=sensor).filter(created_at__gte = form.cleaned_data['start_date']).filter(created_at__lte = form.cleaned_data['end_date'])
            print(queryset)
            dataset = sensor_data_resource.export(queryset)

            download = Download()
            download.owner = request.user
            download.sensors_set = [sensor]
            download.start_date = form.cleaned_data['start_date']
            download.end_date = form.cleaned_data['end_date']
            download.save()

            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="sensor.csv"'
            return response


    # if a GET (or any other method) we'll create a blank form
    else:
        sensor = Sensor.objects.get(id=sensor_id)
        form = SensorExportForm()
        date = datetime.datetime.today().strftime('%Y-%m-%d')
        return render(request, 'logger/export-form.html', {'form': form, 'sensor': sensor,'date': date})


@csrf_exempt
def add_data(request):
    if request.method == 'POST':
        data = request.POST
        sensor = Sensor.objects.get(id=data['node_id'])
        sensor_data = SensorData()
        sensor_data.sensor = sensor
        sensor_data.particulate_matter = data['density']
        sensor_data.created_at = datetime.datetime.fromtimestamp(
        int(data['timestamp']))
        sensor_data.save()
    return JsonResponse(data)

def map_sensors(request):
    sensors = Sensor.objects.all()
    for sensor in sensors:
        if sensor.sensordata_set.last():
            sensor.pm = sensor.sensordata_set.order_by('created_at').last().particulate_matter
        else:
            sensor.pm = 0
    return render(request,'logger/map_sensors.html',{'sensors': sensors})

def heatmap(request):
    sensors = Sensor.objects.all()
    data = []
    for sensor in sensors:
        if sensor.sensordata_set.last():
            pm = sensor.sensordata_set.order_by('created_at').last().particulate_matter
        else:
            pm = 0
        data.append([sensor,pm])
    return render(request,'logger/heatmap.html',{'data': data})

def sensor_detail(request,sensor_id):
    sensor = Sensor.objects.get(id=sensor_id)
    data = sensor.sensordata_set.order_by('-created_at').all()
    for log in data:
        log.created_at = log.created_at - datetime.timedelta(hours = 8)
    return render(request,'logger/sensor_detail.html',{'sensor': sensor, 'data':data})

logger/templates/logger/base.html
{% load staticfiles %}
<html>
    <head>
        <title>PM Serve</title>
        <link rel="stylesheet" href="https://bootswatch.com/3/darkly/bootstrap.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
         integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
         crossorigin=""/>
         <!-- Make sure you put this AFTER Leaflet's CSS -->
       <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
         integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
         crossorigin=""></script>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.css">
       <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.js"></script>
       <script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>
       <script src="https://cdn.jsdelivr.net/npm/leaflet.heat@0.2.0/dist/leaflet-heat.min.js"></script>
    </head>
    <body>
    <div class="page-header" style="margin: 0">
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">PM Serve</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="/sensors/map">Sensor Map <span class="sr-only">(current)</span></a></li>
              <li><a href="/sensors/heatmap">PM Heatmap</a></li>
              <li><a href="/sensors/export">Export Data</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{user.username}}</a></li>
              <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
              {% else %}
              <li><a href="/accounts/register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
              {% endif %}
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
    <div class="content container">
        <div class="row">

            {% block content %}
            {% endblock %}

        </div>
    </div>
    <script src="https://bootswatch.com/_vendor/jquery/dist/jquery.min.js"></script>
    <script src="https://bootswatch.com/_vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://bootswatch.com/_assets/js/custom.js"></script>
</body>
</html>

logger/templates/logger/export-form.html
{% extends "base.html" %}

{% block content %}
  <div class="col-lg-12"><h2>{{sensor.name}} data export</h2></div>
  <form action="/sensors/export/{{sensor.id}}" method="post">
    {% csrf_token %}
    <input id="id_sensor" type="hidden" name="sensor" value="{{ sensor.id }}">
    <div class="form-group">
      <label for="id_start_date">Start Date</label>
      <input id="id_start_date"  class="form-control"  type="date" name="start_date" value="{{ date }}" required /></p>
    </div>
    <div class="form-group">
      <label for="id_end_date">End Date:</label>
      <input id="id_end_date"  class="form-control"  type="date" name="end_date" value="{{ date }}" required /></p>
    </div>
    <div class="form-group">
      <input type="submit"  class="btn btn-default"  value="Submit" />
    </div>
  </form>
{% endblock %}

logger/templates/logger/export-poly.html
{% extends "base.html" %}

{% block content %}
  <div class="col-lg-12"><h2>Sensor data export</h2></div>
  <div class="col-lg-6">
    <div id="mapid" style="width: 100%; height: 400px;"></div>
  </div>
  <div class="col-lg-6">
  <form action="/sensors/export/" method="post">
    {% csrf_token %}
    <input id="id_sensor" type="hidden" name="sensor" value="{{ sensor.id }}">
    <input id="id_mul_sensors" type="hidden" name="mul_sensors">
    <div class="form-group">
      <label for="id_start_date">Start Date</label>
      <input id="id_start_date"  class="form-control"  type="date" name="start_date" value="{{ date }}" required /></p>
    </div>
    <div class="form-group">
      <label for="id_end_date">End Date:</label>
      <input id="id_end_date"  class="form-control"  type="date" name="end_date" value="{{ date }}" required /></p>
    </div>
    <div class="form-group">
      <input type="submit"  class="btn btn-default"  value="Submit" />
    </div>
  </form>
</div>
  <script>

    var mymap = L.map('mapid').setView([16.405804, 120.59852], 18);

    L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {

      maxZoom: 18,
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(mymap);

    var drawnItems = new L.FeatureGroup();
     mymap.addLayer(drawnItems);
     var drawControl = new L.Control.Draw({
         edit: {
             featureGroup: drawnItems
         }
     });
     mymap.addControl(drawControl);



    var markers = [];
    var selected_markers = [];
    {% for sensor in sensors %}
      marker = L.marker([{{ sensor.coordinates.y }}, {{ sensor.coordinates.x }}]);
      marker.addTo(mymap);
      marker.bindPopup("<b>{{sensor.id}} {{sensor.name}}</b><br>{{sensor.description}}");
      console.log(marker.toGeoJSON());
      obj = {'id': {{sensor.id}},'marker': marker.toGeoJSON()};
      markers.push(obj);
    {% endfor %}
    //console.log(markers);

    mymap.on(L.Draw.Event.CREATED, function (e) {
      var type = e.layerType,
          layer = e.layer;
      points = [];
      markers.forEach(function(point) {
          points.push(point.marker.geometry.coordinates)
      });
      bound = layer.toGeoJSON().geometry.coordinates
      var ptsWithin = turf.pointsWithinPolygon(turf.points(points), turf.polygon(bound));
      console.log(ptsWithin);
      mymap.addLayer(layer);

      selected_markers = []

      markers.forEach(function(point) {
        ptsWithin.features.forEach(function(within_point) {
          if(point.marker.geometry.coordinates[0]==within_point.geometry.coordinates[0] && point.marker.geometry.coordinates[1]==within_point.geometry.coordinates[1]){
              selected_markers.push(point.id)
          }
        });

      });
      console.log(selected_markers);
      $('#id_mul_sensors').val(JSON.stringify(selected_markers));
   });

  </script>
{% endblock %}

logger/templates/logger/heatmap.html
{% extends "base.html" %}

{% block content %}
    <div class="col-lg-12"><h2>Sensors</h2></div>
    <div class="col-lg-12">
    <div id="mapid" style="width: 100%; height: 400px;"></div>
    <script>

    	var mymap = L.map('mapid').setView([16.405804, 120.59852], 18);

      L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
      	maxZoom: 18,
      	attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      }).addTo(mymap);
      {% for sensor in data %}
        marker = L.marker([{{ sensor.0.coordinates.y }}, {{ sensor.0.coordinates.x }}]);
        //marker.addTo(mymap);
        //marker.bindPopup("<b>{{sensor.0.id}} {{sensor.0.name}}</b><br>{{sensor.0.description}}");
      {% endfor %}

      var heat = L.heatLayer([
        {% for sensor in data %}
      	   [{{ sensor.0.coordinates.y }}, {{ sensor.0.coordinates.x }}, {{sensor.1}}],
      	{% endfor %}
      ], {radius: 30, max:0.46}).addTo(mymap);

    </script>
  </div>
{% endblock %}

logger/templates/logger/map_sensors.html
{% extends "base.html" %}

{% block content %}
    <div class="col-lg-12"><h2>Sensors</h2></div>
    <div class="col-lg-12">
    <div id="mapid" style="width: 100%; height: 400px;"></div>
    <script>

    	var mymap = L.map('mapid').setView([16.405804, 120.59852], 18);

      L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
      	maxZoom: 18,
      	attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      }).addTo(mymap);
      {% for sensor in sensors %}
        marker = L.marker([{{ sensor.coordinates.y }}, {{ sensor.coordinates.x }}]);
        marker.addTo(mymap);
        marker.bindPopup("<b><a href='/sensors/detail/{{sensor.id}}'>{{sensor.id}} {{sensor.name}}</a></b> \
                          <br>{{sensor.description}} \
                          <br>Current Reading: {{sensor.pm}} μg/m^3 \
                          ");
      {% endfor %}

    </script>
  </div>
{% endblock %}

logger/templates/logger/sensor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="col-lg-12">
    <h2>Sensor: {{sensor.name}}</h2>
  </div>
  <div class="col-lg-6">


  <div id="mapid" style="width: 100%; height: 60%;"></div>
  <script>

    var mymap = L.map('mapid').setView([16.405804, 120.59852], 18);

    L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
      maxZoom: 18,
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(mymap);

      marker = L.marker([{{ sensor.coordinates.y }}, {{ sensor.coordinates.x }}]);
      marker.addTo(mymap);
      marker.bindPopup("<b>{{sensor.id}} {{sensor.name}}</b><br>{{sensor.description}}");

  </script>
</div>
<div class="col-lg-6" style="height:100%;">
  <ul>
  <li>Name: {{sensor.name}}</li>
  <li>Description: {{sensor.description}}</li>
  <li>Address: {{sensor.address}}</li>
  <li>Latitude: {{sensor.coordinates.y}}</li>
  <li>Longitude: {{sensor.coordinates.x}}</li>
</ul>
<a href="/sensors/export/{{sensor.id}}" class="btn btn-default" role="button">Export Data</a>
<div class="table-responsive" style="height:40%">
<table class="table table-striped">
  <thead>
    <tr>
      <th>PM 2.5 Density (μg/m^3)</th>
      <th>Created at</th>
      <th>Received at</th>
    </tr>
  </thead>
  <tbody>
    {% for row in data %}
    <tr>
      <td>{{row.particulate_matter}}</td>
      <td>{{row.created_at|date:'Y-m-d H:i:s'}}</td>
      <td>{{row.received_at|date:'Y-m-d H:i:s'}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>
{% endblock %}

logger/templates/logger/sensor_list.html
{% extends "base.html" %}

{% block content %}
  <div class="col-lg-12"><h2>Sensor List</h2></div>
  <ul>
  {% for sensor in object_list %}
    <li><a href="/sensors/detail/{{sensor.id}}" >{{sensor.name}}</a></li>
  {% endfor %}
  </ul>
{% endblock %}